apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeclarity.sbom-db.name" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "kubeclarity.sbom-db.labels" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kubeclarity.sbom-db.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "kubeclarity.sbom-db.name" . }}
    spec:
      serviceAccountName: {{ include "kubeclarity.sbom-db.name" . }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
      {{- if not .Values.global.openShiftRestricted }}
      securityContext:
        fsGroup: 1000
      {{- end }}
      containers:
        - name: sbom-db
          image: '{{ .Values.global.docker.registry }}/kubeclarity-sbom-db:{{ index .Values "kubeclarity-sbom-db" "docker" "imageTag" }}'
          imagePullPolicy: {{ index .Values "kubeclarity-sbom-db" "docker" "imagePullPolicy" }}
          args:
            - run
            - --log-level
            - {{ index .Values "kubeclarity-sbom-db" "logLevel" }}
          env:
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8081
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          securityContext:
          {{- if not .Values.global.openShiftRestricted }}
          {{- toYaml (index .Values "kubeclarity-sbom-db" "securityContext") | nindent 12 }}
          {{- end }}
            capabilities:
              drop:
                - all
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
{{- toYaml (index .Values "kubeclarity-sbom-db" "resources") | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
