{{- if .Values.yaraRuleServer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openclarity.yaraRuleServer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "openclarity.yaraRuleServer.labels.standard" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.yaraRuleServer.serviceAccount.automountServiceAccountToken }}
{{- end -}}
