builds:
  -
    id: "cli"
    dir: cli
    binary: kubeclarity-cli
    env:
      - CGO_ENABLED=0
    ldflags: "-s -w -X github.com/cisco-open/kubei/cli/pkg.GitRevision={{ .Version }}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  -
    id: "cli"
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

    # Additional files/template/globs we want to add to the archive.
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

# Change the default artifacts folder
dist: goreleaser_artifacts

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^workflow:'
