{{- if index .Values "kubeclarity-grype-server" "enabled" }}
{{- $affinity := (coalesce (index .Values "kubeclarity-grype-server" "affinity") .Values.global.affinity) -}}
{{- $nodeSelector := (coalesce (index .Values "kubeclarity-grype-server" "nodeSelector") .Values.global.nodeSelector) -}}
{{- $podSecurityContext := (coalesce (index .Values "kubeclarity-grype-server" "podSecurityContext") .Values.global.podSecurityContext) -}}
{{- $containerSecurityContext := (coalesce (index .Values "kubeclarity-grype-server" "containerSecurityContext") .Values.global.containerSecurityContext) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeclarity.grype-server.name" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "kubeclarity.grype-server.labels" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kubeclarity.grype-server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "kubeclarity.grype-server.name" . }}
    spec:
      serviceAccountName: {{ include "kubeclarity.grype-server.name" . }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
      securityContext:
      {{- toYaml $podSecurityContext | nindent 8 }}
      {{- if $affinity }}
      affinity: {{- toYaml $affinity | nindent 8 }}
      {{- end }}
      {{- if $nodeSelector }}
      nodeSelector: {{- toYaml $nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: grype-server
          image: '{{ index .Values "kubeclarity-grype-server" "docker" "imageRepo" }}/grype-server:{{ index .Values "kubeclarity-grype-server" "docker" "imageTag" }}'
          imagePullPolicy: {{ index .Values "kubeclarity-grype-server" "docker" "imagePullPolicy" }}
          args:
            - run
            - --log-level
            - {{ index .Values "kubeclarity-grype-server" "logLevel" }}
          env:
            - name: DB_ROOT_DIR
              value: /tmp/
{{- if index .Values "kubeclarity-runtime-scan" "httpsProxy" }}
            - name: HTTPS_PROXY
              value: {{ index .Values "kubeclarity-runtime-scan" "httpsProxy" }}
{{- end}}
{{- if index .Values "kubeclarity-runtime-scan" "httpProxy" }}
            - name: HTTP_PROXY
              value: {{ index .Values "kubeclarity-runtime-scan" "httpProxy" }}
{{- end}}
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8080
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          securityContext:
          {{- toYaml $containerSecurityContext | nindent 12 }}
          resources:
{{- toYaml (index .Values "kubeclarity-grype-server" "resources") | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
{{- end}}
