{{- if .Values.ui.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openclarity.ui.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "openclarity.ui.labels.standard" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.ui.serviceAccount.automountServiceAccountToken }}
{{- end -}}
