{{- if .Values.apiserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openclarity.apiserver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "openclarity.apiserver.labels.standard" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.apiserver.serviceAccount.automountServiceAccountToken }}
{{- end -}}
