services:
  alpine:
    image: alpine:3.17.0@sha256:c0d488a800e4127c334ad20d61d7bc21b4097540327217dfab52262adc02380c
    command: ["sleep", "infinity"]
    networks:
      - asset
    labels:
      scanconfig: test

networks:
  asset:
    name: ${COMPOSE_PROJECT_NAME}-asset
