#cloud-config
package_upgrade: true
packages:
  - docker.io
write_files:
  - path: /opt/openclarity/scanconfig.yaml
    permissions: "0644"
    content: |
      {{- .ScannerCLIConfig | nindent 6 }}
  - path: /etc/systemd/system/openclarity-scanner.service
    permissions: "0644"
    content: |
      [Unit]
      Description=OpenClarity scanner job
      Requires=docker.service
      After=network.target docker.service
      
      [Service]
      Type=oneshot
      WorkingDirectory=/opt/openclarity
      ExecStartPre=mkdir -p /var/opt/openclarity
      ExecStartPre=docker pull {{ .ScannerImage }}
      ExecStartPre=docker network create openclarity
      ExecStart=docker run --rm --name %n --privileged \
          -v /:/hostfs \
          -v /dev:/dev \
          -v /opt/openclarity:/opt/openclarity \
          -v /run:/run \
          -v /var/opt/openclarity:/var/opt/openclarity \
          -v /mnt:/mnt \
          --network openclarity \
          {{ .ScannerImage }} \
          scan \
          --config /opt/openclarity/scanconfig.yaml \
          --server {{ .APIServerAddress }} \
          --mount-attached-volume \
          --asset-scan-id {{ .AssetScanID }} \
          --output /var/opt/openclarity
      
      [Install]
      WantedBy=multi-user.target

runcmd:
  - [ systemctl, daemon-reload ]
  - [ systemctl, start, docker.service ]
  - [ systemctl, start, openclarity-scanner.service ]
