apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openclarity.grypeServer.name" . }}
  labels: {{- include "openclarity.grypeServer.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "openclarity.grypeServer.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.grypeServer.replicaCount }}
  template:
    metadata:
      labels: {{- include "openclarity.grypeServer.labels.standard" . | nindent 8 }}
    spec:
      {{- if .Values.grypeServer.affinity }}
      affinity: {{- .Values.grypeServer.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.grypeServer.nodeSelector }}
      nodeSelector: {{- .Values.grypeServer.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.grypeServer.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.grypeServer.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.grypeServer.tolerations }}
      tolerations: {{- .Values.grypeServer.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: grype-server
          image: {{ include "openclarity.images.image" ( dict "imageRoot" .Values.grypeServer.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.grypeServer.image.pullPolicy | quote }}
          {{- if .Values.grypeServer.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.grypeServer.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          args:
            - run
            - --log-level
            - {{ .Values.grypeServer.logLevel }}
          env:
            - name: DB_ROOT_DIR
              value: /data
          {{- if .Values.grypeServer.resources }}
          resources: {{- toYaml .Values.grypeServer.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /data
              name: db-data
            - mountPath: /tmp
              name: tmp
      volumes:
        - name: db-data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      serviceAccountName: {{ include "openclarity.grypeServer.serviceAccountName" . }}
