{{- if .Values.freshclamMirror.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openclarity.freshclamMirror.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "openclarity.freshclamMirror.labels.standard" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.freshclamMirror.serviceAccount.automountServiceAccountToken }}
{{- end -}}
