apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openclarity.swaggerUI.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "openclarity.swaggerUI.labels.standard" . | nindent 4 }}
data:
  swagger-config.json: |
    {
        "urls": [
            {
                "name": "OpenClarity API",
                "url": "/api/openapi.json"
            }
        ]
    }
