apiVersion: v1
kind: Service
metadata:
  name: {{ include "openclarity.swaggerUI.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "openclarity.swaggerUI.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector: {{- include "openclarity.swaggerUI.labels.matchLabels" . | nindent 4 }}
