services:
  postgresql:
    image: ${OPENCLARITY_POSTGRESQL_CONTAINER_IMAGE:-docker.io/bitnami/postgresql:16.3.0-debian-12-r23}
    env_file: ./postgres.env
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d openclarity -U openclarity"]
      interval: 10s
      retries: 60

  apiserver:
    depends_on:
      postgresql:
        condition: service_healthy
