{{- if .Values.gateway.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openclarity.gateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "openclarity.gateway.labels.standard" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.gateway.serviceAccount.automountServiceAccountToken }}
{{- end -}}
