name: Dependencies

on:
  workflow_dispatch:
  schedule:
    # At 01:00 on Monday: https://crontab.guru/#0_1_*_*_1
    - cron: '0 1 * * 1'

jobs:
  renovate:
    name: Renovate Sync
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate Bot
        id: auth
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        with:
          app-id: ${{ secrets.OPENCLARITY_BOT_APP_ID }}
          private-key: ${{ secrets.OPENCLARITY_BOT_PRIVATE_KEY }}

      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 20

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Renovate
        run: make renovate
        env:
          ## Discovery
          # Renovate finds and creates PRs for all repos accessible by auth token.
          # Since we auth only against this repo, no other repos can be accessed.
          RENOVATE_AUTODISCOVER: "true"
          RENOVATE_FORK_PROCESSING: "enabled"
          ## Project sync
          RENOVATE_PLATFORM: "github"
          RENOVATE_PLATFORM_COMMIT: "true"
          RENOVATE_TOKEN: ${{ steps.auth.outputs.token }}
          GITHUB_COM_TOKEN: ${{ steps.auth.outputs.token }}
          # Remove unused fields from PR description
          RENOVATE_PR_BODY_TEMPLATE: "{{{header}}}{{{table}}}{{{warnings}}}{{{notes}}}{{{changelogs}}}"
          RENOVATE_DEPENDENCY_DASHBOARD_HEADER: ""
          RENOVATE_DEPENDENCY_DASHBOARD_O_S_V_VULNERABILITY_SUMMARY: "all"
